<?php include("includes/functions.php"); $random_pass = randomPassword(); ?>

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags-->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Login System Using PHP">
  <meta name="author" content="Joemar">
  <meta name="keywords" content="Login System">

  <!-- Title Page-->
  <title>Sign Up</title>

  <!-- Icons font CSS-->
  <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
  <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
  <!-- Font special for pages-->
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

  <!-- Vendor CSS-->
  <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
  <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

  <!-- Main CSS-->
  <link href="css/main.css" rel="stylesheet" media="all">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

</head>

  <body>
    <div class="page-wrapper bg-blue p-t-100 p-b-100 font-robo">
        <div class="wrapper wrapper--w680">
            <div class="card card-1">
                <div class="card-heading2"></div>
                <div class="card-body">
                    <h2 class="title"><span><a class="link_home" href="index.php">Mar's</a> Login System : Sign Up<span></h2>
                    <form action="insert_user.php" method="POST">

                      <div class="row row-space">
                        <div class="col-2">
                          <div class="input-group">
                            <input id="f_name"type="text" placeholder="First Name" name="first_name" required="required">
                          </div>
                        </div>
                        <div class="col-2">
                          <div class="input-group">
                            <input type="text" type="text" placeholder="Last Name" name="last_name" required="required">
                          </div>
                        </div>
                      </div>
                      <div class="input-group">
                        <input id="email" type="email" class="form-control" placeholder="Email" name="u_email" required="required">
                      </div>
                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                <input id="birthday" class="input--style-1 js-datepicker" type="text" type="date" placeholder="Birthdate" name="u_birthday" required="required">
                                <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <div class="rs-select2 js-select-simple select--no-search">
                                        <select id="gender" name="u_gender" required="required">
                                          <option disabled>Select your Gender</option>
                                          <option>Male</option>
                                          <option>Female</option>
                                          <option>Others</option>
                                        </select>
                                      <div class="select-dropdown"></div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="input-group">
                          <div class="rs-select2 js-select-simple select--no-search">
                              <select id="country" name="u_country" required="required">
                                  <option disabled>Select your Country</option>
                                  <?php foreach($countries as $i => $name) { echo '<option value="' . $i . '">' . $name . '</option>'; } ?>
                              </select>
                              <div class="select-dropdown"></div>
                          </div>
                      </div>
                      <div class="row row-space">
                          <div class="col-2">
                            <label for="copy-text">AUTOGENERATED PASSWORD</label>
                            <h5 class="animate__animated animate__headShake animate__infinite	infinite"><input class='input--style-1' id='copy-text' id='password' type='text' value="<?php echo $random_pass; ?>" name='u_pass' readonly></h5>
                          </div>
                          <div class="col-2">
                            <!--class="button" what if hidden attr-->
                              <button class="btn btn--radius btn--light_blue button" id="copy" type="button"> Copy Password <span class="done" aria-hidden="true"> <?php echo $random_pass; ?> </span></button>
                              <textarea id="empty-field" placeholder="paste here" hidden></textarea>
                          </div>
                      </div>
                      <div class="p-t-20">
                        <a class="has_an_acc" title="Signin" href="signin.php"> Already have an account? </a>
                      </div>
                      <div class="p-t-20">
                        <button id="signup" class="btn btn--radius btn--green" type="submit" name="sign_up">Sign Up</button>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="vendor/select2/select2.min.js"></script>
    <script src="vendor/datepicker/moment.min.js"></script>
    <script src="vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="js/global.js"></script>
  </body>
</html>
<!--
https://getbootstrap.com/docs/4.0/components/forms/

->
